use_frameworks!

platform :ios, '9.0'

target 'ObjectWithAssignCheck_Example' do
  pod 'ObjectWithAssignCheck', :path => '../'

  target 'ObjectWithAssignCheck_Tests' do
    inherit! :search_paths

    
  end
end
